wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/search/", views.search, name="search"),
    path("wiki/new/", views.new, name="new"),
    path("wiki/edit/<str:title>", views.edit, name="edit"),
    path("wiki/delete/<str:title>", views.delete, name="delete"),
    path("wiki/random_page/", views.random_page, name="random_page"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django import forms
from django.shortcuts import render, redirect

from . import util
import markdown2
import random

# class to store content of New Pages
class NewPageForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea())

# class to edit content of Entry Pages
class EditPageForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea())

# index page
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# entry's page
def entry(request, title):
    content = markdown2.markdown(str(util.get_entry(title)))
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "get_entry": util.get_entry(title),
        "content": content,
        "entries": util.list_entries()
    })

# redirect to Search page if entry is invalid
def search(request):
    # Check if method is GET
    if request.method == "GET":
        query = request.GET.get("q") # get the search query
        # if the searched query is found in util.list_entries()
        if(query in util.list_entries()):
             # redirect to a url tag with 'title' as a parameter
            return redirect("encyclopedia:entry", title=query)
        # if not matched any queries in list_entries, redirect to search.html
        else:
            results = []
            for entry in util.list_entries():
                if query.lower() in entry.lower():
                    results.append(entry)
            
            # if a list of "results" is empty, list the default entries
            if not results: 
                # results = entries
                return redirect("encyclopedia:entry", title=query)
            return render(request, "encyclopedia/search.html", {
                "q": query,
                "entries": results
            })
            
            
    # if not GET any queries, present the search.html
    return render(request, "encyclopedia/search.html", {
        "q": None,
        "entries": util.list_entries()
        
    })            

# New page
def new(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            
            # if title in util.list_entries():
            for entry in util.list_entries():
                if title.lower() in entry.lower():
                    return render(request, "encyclopedia/error.html", {
                        "message": "Page already exists!",
                        "title": entry
                        })
            else:
                util.save_entry(title, content)
                return redirect("encyclopedia:entry", title=title)
        else:
            return render(request, "encyclopedia/new.html", {
                "form": form
                })
    else:
        return render(request, "encyclopedia/new.html", {
            "form": NewPageForm()
            })
    
# Edit page
def edit(request, title):
    if request.method == "POST":
        # If the new update is saved, redirect to new entry's page
        form = EditPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return redirect("encyclopedia:entry", title=title)
    else:
        # pre-populated with the existing Markdown content of the page
        return render(request, 'encyclopedia/edit.html', {
            "title": title,
            "content": util.get_entry(title)
        })
    
# delete page
def delete(request, title):
    return render(request, "encyclopedia/delete.html", {
        "title": title,
        "message": util.delete_entry(title)
    })

# random page
def random_page(request):
    entries_list = util.list_entries()
    title = random.choice(entries_list)
    return redirect("encyclopedia:entry", title=title)

wiki/encyclopedia/templates/encyclopedia/delete.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Delete page
{% endblock %}

{% block body %}
    <h2> Delete Page: {{ title }} </h2>
    <div class="container">
        <div style="padding-right: 2%;">
            <h3> {{ message }} </h3>
        </div>
        <div>
            {% if message == "Cannot delete default page" %}
                <img src="https://th.bing.com/th/id/R.e29233349a5e0d260d647b751bc08489?rik=Z7hn%2bRTMhB4i5w&pid=ImgRaw&r=0" alt="description of image" style="height:300px;"> 
            {% else %}
                <img src="https://th.bing.com/th/id/R.a183511a045c39d28e177ce1126873db?rik=%2baX4qHbCRT4LWg&riu=http%3a%2f%2fclipart-library.com%2fnew_gallery%2f178285_troll-face-png-no-background.png&ehk=BbhYgGclaV5h5%2f5BDdiQH0a0mOT4PxffYTFoNMXrEuM%3d&risl=&pid=ImgRaw&r=0" style="height:300px;"> 
            {% endif %}
        </div>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit page
{% endblock %}

{% block body %}
    <h1>Edit Page:</h1>
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        <label for="title">Title:</label>
        <input type="text" name="title" value="{{ title }}">
        <br>
        <label for="content">Content:</label>
        <br>
        <textarea id="content" name="content" value="{{ content }}" style="height: 60vh;">{{ content }}</textarea>
        <br>
        <button type="submit">Save</button>
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {% if get_entry %}
        <button><a href="{% url 'encyclopedia:edit' title %}">Edit page</a></button>
        <span><a href="{% url 'encyclopedia:delete' title %}" style="padding-left: 1%;">Delete page</a></span>
        {{ content|safe }}
    {% else %}
        <h1>No result: {{ title }}</h1>
        <div class="container">
            <div>
                <img src="https://www.acmesystems.it/www/pagenotfound/page_not_found.jpg" alt="description of image" style="height:250px; width: 400px;"> 
            </div>
            <div>
                <h3> The expected entries: </h3>
                <ul>       
                    {% for entry in entries %}
                        <li>
                            <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
                        </li>
                    {% endfor %} 
                    
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1> {{ message }}</h1>
    <div class="container">
        <div>
            <img src="https://i.pinimg.com/236x/01/6e/59/016e592cbe92dfce0d575693e1cb2f07.jpg?nii=t" alt="description of image" style="height:300px;"> 
        </div>
        <div style="padding-left: 2%;">
            <h4>Read more: <a href="{% url 'encyclopedia:entry' title %}">{{ title }}</a></h4>
        </div>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" value="{{ q }}" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h1>Create a new page:</h1>
    <form action="{% url 'encyclopedia:new' %}" method="post">
        {% csrf_token %}
        <label for="title">Title:</label>
        <input type="text" name="title" value="{{ title }}">
        <br>
        <label for="content">Content:</label>
        <br>
        <textarea id="content" name="content" value="{{ content }}"></textarea>
        <br>
        <!-- {{ form.as_p }} -->
        <button type="submit">Save</button>
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/random_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Random page
{% endblock %}

{% block body %}
    <h1>I think you won't see this page!</h1>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search result: {{ q }}</h1>
    <div class="container">
        <div>
            <img src="https://th.bing.com/th/id/R.6d1d67ed67e6fb9b1ea92b1f96b76c06?rik=vXeVl6oT8Sbatw&riu=http%3a%2f%2fclipart-library.com%2fimages_k%2fmeme-face-transparent-background%2fmeme-face-transparent-background-15.png&ehk=fzSMtW3T44FSaR6qzf543PxHzVBWRp%2b5CvP6jU%2fjxnw%3d&risl=&pid=ImgRaw&r=0" style="height: 300px;"> 
        </div>
        <div>
            <h2> Are you looking for?</h2>
            <ul>       
                {% for entry in entries %}
                    <li>
                        <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
                    </li>
                {% endfor %}     
            </ul>
        </div>
    </div>

{% endblock %}